# Generated by Django 2.2.4 on 2019-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='musics')),
                ('title', models.CharField(max_length=100)),
                ('lyricst', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('release_date', models.DateField()),
                ('music_company', models.CharField(max_length=300)),
            ],
        ),
    ]
