# Generated by Django 2.2.4 on 2019-08-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicsOfArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField()),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='language',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
