# Generated by Django 2.2.4 on 2019-08-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_music_app', '0002_auto_20190809_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
